-- ══════════════════════════════════════════════════════════════════
-- ROHAH POS — Seed Data
-- Paste semua ini di Supabase SQL Editor → Run
-- ══════════════════════════════════════════════════════════════════

-- 1. AKUN KARYAWAN AWAL
INSERT INTO employees (name, role, pin, active) VALUES
  ('Owner ROHAH',   'owner',   '0000', true),
  ('Manager ROHAH', 'manager', '3333', true),
  ('Admin ROHAH',   'admin',   '2222', true),
  ('Kasir 1',       'kasir',   '1111', true),
  ('Kasir 2',       'kasir',   '1234', true);

-- 2. SEMUA MENU ITEMS
INSERT INTO menu_items (name, category, price, emoji, active) VALUES
  ('Mie Yamin Tasik Manis',      'Main Dish',  35000, '🍜', true),
  ('Mie Yamin Tasik Asin',       'Main Dish',  35000, '🍜', true),
  ('Mie Ayam Kampung',           'Main Dish',  30000, '🍜', true),
  ('Nasi Sop Buntut',            'Main Dish',  65000, '🍲', true),
  ('Nasi Sop Iga',               'Main Dish',  65000, '🍲', true),
  ('Nasi Ayam Bakar',            'Main Dish',  45000, '🍗', true),
  ('Nasi Ayam Goreng',           'Main Dish',  45000, '🍗', true),
  ('Rice Bowl Se''i Sapi',       'Main Dish',  40000, '🥩', true),
  ('Rice Bowl Chicken Teriyaki', 'Main Dish',  35000, '🍱', true),
  ('Chicken Steak',              'Main Dish',  65000, '🥩', true),
  ('Kwetiaw Goreng',             'Main Dish',  37000, '🍝', true),
  ('Nasi Goreng Special',        'Main Dish',  37000, '🍳', true),
  ('Bubur Ayam',                 'Main Dish',  25000, '🥣', true),
  ('Tekwan',                     'Main Dish',  30000, '🍵', true),
  ('Pangsit Kuah',               'Main Dish',  25000, '🥟', true),
  ('Asinan Betawi',              'Side Dish',  30000, '🥗', true),
  ('Asinan Buah',                'Side Dish',  30000, '🍇', true),
  ('Pempek (7 pcs)',             'Side Dish',  45000, '🐟', true),
  ('Singkong Keju Manis',        'Side Dish',  27500, '🧀', true),
  ('Singkong Keju Asin',         'Side Dish',  27500, '🧀', true),
  ('French Fries',               'Side Dish',  20000, '🍟', true),
  ('Dimsum Ayam (4 pcs)',        'Side Dish',  25000, '🥟', true),
  ('Dimsum Mix (6 pcs)',         'Side Dish',  40000, '🥟', true),
  ('Cilok Goreng',               'Side Dish',  18000, '🟠', true),
  ('Croissant',                  'Side Dish',  27000, '🥐', true),
  ('Cireng',                     'Side Dish',  18000, '🟡', true),
  ('Americano Hot/Ice',          'Coffee',     25000, '☕', true),
  ('Rohah Signature',            'Coffee',     25000, '☕', true),
  ('Long Black',                 'Coffee',     25000, '☕', true),
  ('Cappuccino',                 'Coffee',     25000, '☕', true),
  ('Hazelnut Latte',             'Coffee',     25000, '☕', true),
  ('Pandan Latte',               'Coffee',     25000, '☕', true),
  ('Butterscotch Original',      'Coffee',     25000, '☕', true),
  ('Butterscotch Sea Salt',      'Coffee',     25000, '☕', true),
  ('Gula Aren Original',         'Coffee',     25000, '☕', true),
  ('Gula Aren Klepon Latte',     'Coffee',     25000, '☕', true),
  ('Caramel Latte',              'Coffee',     25000, '☕', true),
  ('Latte',                      'Coffee',     25000, '🥛', true),
  ('Frappe de Tiramisu',         'Coffee',     30000, '🧊', true),
  ('Nutty Caramel Latte',        'Coffee',     30000, '☕', true),
  ('Nutella Latte',              'Coffee',     25000, '☕', true),
  ('Dark Chocolate',             'Non-Coffee', 25000, '🍫', true),
  ('Klepon',                     'Non-Coffee', 25000, '🟢', true),
  ('Red Velvet',                 'Non-Coffee', 25000, '❤️', true),
  ('Thai Tea',                   'Non-Coffee', 25000, '🧡', true),
  ('Taro Original',              'Non-Coffee', 25000, '🟣', true),
  ('Taro Sea Salt',              'Non-Coffee', 25000, '🟣', true),
  ('Matcha Latte',               'Non-Coffee', 25000, '🍵', true),
  ('Matcha Sea Salt',            'Non-Coffee', 25000, '🍵', true),
  ('Snow Ice',                   'Non-Coffee', 35000, '🧊', true),
  ('Lemon Tea',                  'Tea',        18000, '🍋', true),
  ('Lychee Tea',                 'Tea',        18000, '🍇', true),
  ('Lemon Lychee Tea',           'Tea',        25000, '🍋', true),
  ('Teh Dilmah Peppermint',      'Tea',        25000, '🫖', true),
  ('Teh Dilmah Ginger & Mint',   'Tea',        25000, '🫖', true),
  ('Teh Dilmah Vanilla',         'Tea',        25000, '🫖', true),
  ('Teh Dilmah Earl Grey',       'Tea',        25000, '🫖', true),
  ('Teh Dilmah Chamomile',       'Tea',        25000, '🌼', true),
  ('Teh Dilmah Green Tea',       'Tea',        25000, '🍵', true),
  ('Teh Dilmah Coconut & Mango', 'Tea',        25000, '🥥', true),
  ('Artisan Tea Chamomile',      'Tea',        25000, '🌼', true),
  ('Artisan Tea Coffee Gayo',    'Tea',        25000, '☕', true),
  ('Artisan Tea Green Tea',      'Tea',        25000, '🍵', true),
  ('Artisan Tea Rose Flower',    'Tea',        25000, '🌺', true),
  ('Kerupuk Putih',              'Toppings',    4500, '🍘', true),
  ('Nasi Putih',                 'Toppings',    7000, '🍚', true),
  ('Telur Ceplok/Rebus',         'Toppings',    5000, '🥚', true);

-- 3. SAMPLE CUSTOMERS (loyalty)
INSERT INTO customers (name, phone, points, tier, visits, last_visit) VALUES
  ('Budi Santoso',  '0812-3456-7890', 2840, 'Gold',     47, '2026-04-30'),
  ('Sari Dewi',     '0813-2345-6789', 1200, 'Silver',   22, '2026-05-01'),
  ('Ahmad Fauzi',   '0821-4567-8901', 4500, 'Platinum', 76, '2026-05-01'),
  ('Rina Putri',    '0857-3456-7890',  350, 'Bronze',    8, '2026-04-28'),
  ('Dodi Prasetyo', '0878-2345-6789', 1800, 'Silver',   31, '2026-04-30');
